services:
  openvpn-as:
    image: openvpn/openvpn-as
    container_name: openvpn-as
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openvpn.rule=Host(`openvpn.danlutsevych.online`)"
      - "traefik.http.routers.openvpn.entrypoints=websecure"
      - "traefik.http.routers.openvpn.tls=true"
      - "traefik.http.routers.openvpn.tls.certresolver=myresolver"
      - "traefik.http.services.openvpn.loadbalancer.server.port=943"
    cap_add:
      - NET_ADMIN
      - MKNOD
    devices:
      - /dev/net/tun
    ports:
      - "943:943" # Admin UI / Client UI
      - "3443:443" # OpenVPN over HTTPS
      - "1194:1194/udp" # OpenVPN UDP
    volumes:
      - openvpn-data:/openvpn
