import dayjs from "dayjs";
import { IMaterialList } from "./MaterialsListModels";

export const mockMaterialsList: IMaterialList[] = [
  {
    id: 1,
    name: "Textile",
    materialListDescription: "",
    groups: [
      {
        groupCode: "01",
        groupName: "Velours",
        availableColors: ["yellow", "black", "white", "blue", "pink", "red"],
        items: [
          {
            vendorCode: "01001",
            color: "yellow",
            purchasePrice: 30,
            balance: "write-off",
            consumerPrice: 90,
            maximumPrice: 100,
            wholesalePrice: 70,
            quantity: 10,
            itemDescription: "Nice yellow textile",
            shipments: [
              {
                status: "in-stock",
                date: dayjs("2024-01-03").toDate(),
                invoice: "A2023-012",
                provider: "LLC TEXTILE",
                client: "Shown Melt",
                guarantee: dayjs("2024-12-14").toDate(),
                shipmentHistory: [
                  {
                    shipmentType: "from-provider",
                    price: 120,
                    date: dayjs("2024-01-03").toDate(),
                    stockName: "Kyiv #1",
                    invoice: "A2023-012-K",
                    serialNumber: "1512038526236",
                    client: null,
                  },
                  {
                    shipmentType: "to-client",
                    price: 120,
                    date: dayjs("2024-01-02").toDate(),
                    stockName: "Kyiv #2",
                    invoice: "A2023-012-K",
                    serialNumber: "1352672344",
                    client: "Shown Melt",
                  },
                ],
              },
              {
                status: "in-stock",
                date: dayjs("2024-02-10").toDate(),
                invoice: "B2023-045",
                provider: "Global Goods Inc.",
                client: "Tech Solutions",
                guarantee: dayjs("2025-02-10").toDate(),
                shipmentHistory: [
                  {
                    shipmentType: "from-provider",
                    price: 300,
                    date: dayjs("2024-02-10").toDate(),
                    stockName: "Lviv #1",
                    invoice: "B2023-045-L",
                    serialNumber: "1623057489236",
                    client: null,
                  },
                  {
                    shipmentType: "from-provider",
                    price: 320,
                    date: dayjs("2024-02-15").toDate(),
                    stockName: "Lviv #1",
                    invoice: "B2023-045-L1",
                    serialNumber: "16230536363",
                    client: null,
                  },
                  {
                    shipmentType: "from-provider",
                    price: 315,
                    date: dayjs("2024-02-17").toDate(),
                    stockName: "Lviv #1",
                    invoice: "B2023-045-L2",
                    serialNumber: "16230536367",
                    client: null,
                  },
                  {
                    shipmentType: "to-client",
                    price: 300,
                    date: dayjs("2024-02-15").toDate(),
                    stockName: "Lviv #2",
                    invoice: "B2023-045-L",
                    serialNumber: "1623057489236",
                    client: "Tech Solutions",
                  },
                ],
              },
              {
                status: "sold-out",
                date: dayjs("2024-03-22").toDate(),
                invoice: "C2023-078",
                provider: "Universal Supplies",
                client: "Retail Mart",
                guarantee: dayjs("2025-03-22").toDate(),
                shipmentHistory: [
                  {
                    shipmentType: "from-provider",
                    price: 250,
                    date: dayjs("2024-03-22").toDate(),
                    stockName: "Odessa #1",
                    invoice: "C2023-078-O",
                    serialNumber: "1750283946537",
                    client: null,
                  },
                  {
                    shipmentType: "to-client",
                    price: 250,
                    date: dayjs("2024-03-25").toDate(),
                    stockName: "Odessa #2",
                    invoice: "C2023-078-O",
                    serialNumber: "1750283946537",
                    client: "Retail Mart",
                  },
                ],
              },
            ],
          },
          {
            vendorCode: "01002",
            color: "white",
            purchasePrice: 30,
            balance: "write-off",
            consumerPrice: 90,
            maximumPrice: 100,
            wholesalePrice: 70,
            quantity: 24,
          },
        ],
        groupDescription: "",
      },
      {
        groupCode: "02",
        groupName: "Cotton",
        availableColors: ["yellow", "black", "white", "blue", "pink", "red"],
        items: [
          {
            vendorCode: "02001",
            color: "yellow",
            purchasePrice: 50,
            balance: "write-off",
            consumerPrice: 120,
            maximumPrice: 130,
            wholesalePrice: 90,
            quantity: 55,
          },
          {
            vendorCode: "02002",
            color: "black",
            purchasePrice: 50,
            balance: "write-off",
            consumerPrice: 120,
            maximumPrice: 130,
            wholesalePrice: 90,
            quantity: 673,
          },
        ],
        groupDescription: "",
      },
      {
        groupCode: "04",
        groupName: "Polyester",
        availableColors: ["yellow", "black", "white", "blue", "pink", "red"],
        items: [
          {
            vendorCode: "04001",
            color: "black",
            purchasePrice: 50,
            balance: "write-off",
            consumerPrice: 120,
            maximumPrice: 130,
            wholesalePrice: 90,
            quantity: 55,
          },
        ],
        groupDescription: "",
      },
      {
        groupCode: "08",
        groupName: "Viscose",
        availableColors: [
          "yellow",
          "black",
          "white",
          "blue",
          "pink",
          "red",
          "green",
        ],
        items: [
          {
            vendorCode: "08001",
            color: "green",
            purchasePrice: 50,
            balance: "write-off",
            consumerPrice: 120,
            maximumPrice: 130,
            wholesalePrice: 90,
            quantity: 55,
          },
        ],
        groupDescription: "",
      },
    ],
  },
  {
    id: 2,
    name: "Generators",
    materialListDescription: "",
    groups: [
      {
        groupCode: "11",
        groupName: "John Deere MTJ-21",
        availableColors: ["yellow", "black", "white", "blue", "pink", "red"],
        items: [
          {
            vendorCode: "11001",
            color: "yellow",
            purchasePrice: 3000,
            balance: "write-off",
            consumerPrice: 9000,
            maximumPrice: 10000,
            wholesalePrice: 7000,
            quantity: 1,
          },
          {
            vendorCode: "11002",
            color: "black",
            purchasePrice: 3000,
            balance: "in-stock",
            consumerPrice: 9000,
            maximumPrice: 10000,
            wholesalePrice: 7000,
            quantity: 12,
          },
        ],
        groupDescription: "",
      },
    ],
  },
];
