// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3W5UwgPShpQ3xC83dorCOxRp3sQ2bTz0',
    appId: '1:777303258538:web:6666aad64689a16ddfa7d3',
    messagingSenderId: '777303258538',
    projectId: 'tennis-5b1a9',
    authDomain: 'tennis-5b1a9.firebaseapp.com',
    storageBucket: 'tennis-5b1a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM93x09KowQKfHHwVnNKWS326gZ_H5ZnU',
    appId: '1:777303258538:android:98fc9feb164ba713dfa7d3',
    messagingSenderId: '777303258538',
    projectId: 'tennis-5b1a9',
    storageBucket: 'tennis-5b1a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJstngLYMDm-ORD-tYKT-GevccOltQQ8I',
    appId: '1:777303258538:ios:3590bdf309eab1e8dfa7d3',
    messagingSenderId: '777303258538',
    projectId: 'tennis-5b1a9',
    storageBucket: 'tennis-5b1a9.appspot.com',
    iosBundleId: 'com.example.tennisApp',
  );
}
