services:
  mongo:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local
