name: Workflow A
on:
  push:
    branches:
      - base

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create artifact
        run: echo "data from A" > data.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-from-A
          path: data.txt
