name: Mongo

on:
  push:
    branches:
      - base
    paths:
      - "mongo/**"

jobs:
  mongo:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Save mongo environment file
        run: echo "${{ vars.MONGO_ENV }}" > mongo/.env

      - name: Remove all <none> images and dangling images
        run: docker image prune -f

      - name: Docker Compose up
        run: docker compose up -d --build
        working-directory: ./mongo
